name: dysvoix
description: "Application DysVoix - Aide à l'élocution pour enfants."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  record: ^6.2.0
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets section for local JSON, images, and audio
  assets:
    - assets/data/
    - assets/images/
    - assets/audio/
